Update faz function

diff --git a/dot_config/zsh/functions/faz b/dot_config/zsh/functions/faz
--- a/dot_config/zsh/functions/faz
+++ b/dot_config/zsh/functions/faz
@@ -1,18 +1,21 @@
 # Fuzzy Azure account switch
-function faz() {
-  # query='[].{name: name, subscriptionId: id}'
-  local account="$(az account list -o table \
-    --query '[].{tenant: tenantDisplayName, name: name, subscriptionId: id}' | \
-    fzf --header-lines=2 --nth='1,2' \
-        --height="50%" \
-        --min-height=17 \
-        --preview='az account show -s {-1} -o json | jq -C' \
-      | rev | cut -d' ' -f1 | rev
-  )"
-  if [[ -n $account ]]; then
-    az account set --subscription $account
-  else
-    echo "account unchanged"
-  fi
-  az account show
-}
+# query='[].{name: name, subscriptionId: id}'
+if [[ ! "$(command -v "fzf")" ]] || [[ ! "$(command -v "az")" ]]; then
+  echo "missing fzf or az"
+  exit 1
+fi
+
+local account="$(az account list -o table \
+  --query '[].{tenant: tenantDisplayName, name: name, subscriptionId: id}' | \
+  fzf --header-lines=2 --nth='1,2' \
+      --height="50%" \
+      --min-height=17 \
+      --preview='az account show -s {-1} -o json | jq -C' \
+    | rev | cut -d' ' -f1 | rev
+)"
+if [[ -n $account ]]; then
+  az account set --subscription $account
+else
+  echo "account unchanged"
+fi
+az account show
